# Select language
language: python

# Select python version
python:
 - "2.6"
 - "2.7"
# - "3.2" texttable is not supporting this version!
 - "3.3"
 - "3.4"
 - "3.5"
 - "3.6"
 - "3.6-dev"
 - "3.7-dev"
 - "nightly"

# Select OS
os:
 - "linux"

# Install requirements
install:
 - "pip install --upgrade setuptools"
 - "pip install --upgrade -r requirements.txt"

# Run
script:
- "python scripts/__travis_test__.py"