# Select language
language: python

# Select python version
python:
# - "2.6" paramiko not supported
 - "2.7"
# - "3.2" texttable is not supporting this version!
# - "3.3" paramiko not supported
 - "3.4"
 - "3.5"
 - "3.6"
 - "3.6-dev"
# - "3.7-dev" error at the moment: https://travis-ci.org/viraintel/OWASP-Nettacker/jobs/332849350
# - "nightly" error at the moment: https://travis-ci.org/viraintel/OWASP-Nettacker/jobs/332849351

# Select OS
os:
 - "linux"

# Run
script:
- "python scripts/__travis_test__.py"